sudo: required
 
language: bash 

services:
  - docker

before_install:
- docker pull mboehme/corebench

script: ./run.sh corebench "cd /root/corebench; ./executeTests.sh test-all make /root/corebench"

